### ISSUE TITLE
v8.0.0

### ISSUE THREAD

**Issue by evanshortiss** [evanshortiss/env-var#156]
Preparing for a v8.0.0 release. 

I will push to the `typescript-refactor` branch in the next few days with a working codebase that handles some or all of these items:

- [ ] Rewrite module in TypeScript
- [ ] Support for non Node.js/React environments #155 
- [ ] Deno support #153 
- [ ] Support a `description` function #142 
- [ ] Add option to make all variables required by default #147
- [ ] Update documentation
- [ ] Create a migration guide for API changes from v7 to v8

**Comment by evanshortiss** [comment]
Notes: 

* Removed ability to override built-in accessors
* Set minimum engine version to Node.js 12.x
* Changed extension API. Now requires invoking the extension via `usingExtension(fn)`
* The `accessors` property is no longer attached to `EnvInstance`  (the return value of `from()`)
* Removed the default exported "convenience" logger. Developers now must create a logger using the exported function
* Changed the built in logger to perform a production mode check using a boolean instead of a "prod" string

**Comment by stuft2** [comment]
I do not know much about Deno but I've published dozens of packages supporting CJS and ESM outputs. Are you open to having help with this?

**Comment by evanshortiss** [comment]
@stuft2 absolutely. I don't have the bandwidth to work on this project. If you do, that'd be wonderful. Ultimately, I don't think a full TypeScript rewrite is even necessary or beneficial, so maybe there's a quick way to get it done?
